#@ load("@ytt:library", "library")
#@ load
##@ load("/quarks-secret.star", "quarks_secret_enabled")
##! !!!TODO: fix please /quarks-secret

#@ if quarks_secret_enabled()
--- #@ template.replace(library.get("quarks-secret").eval())
#@ end
